# Site settings
title: Omer Aslam
email: omeraslam07@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 My first blog. Here I share my technical experiences and much more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://omeraslam.com" # the base hostname & protocol for your site
twitter_username: omeraslam
github_username:  omeraslam

# Build settings
markdown: kramdown
